export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const PROFILE_FETCH_USER_REQUEST = 'PROFILE_FETCH_USER_REQUEST';
export const PROFILE_FETCH_USER_SUCCESS = 'PROFILE_FETCH_USER_SUCCESS';
export const PROFILE_FETCH_USER_FAILED = 'PROFILE_FETCH_USER_FAILED';
export const PROFILE_FETCH_USER_RESET = 'PROFILE_FETCH_USER_RESET';

export const PROFILE_FETCH_PUBLIC_REQUEST = 'PROFILE_FETCH_PUBLIC_REQUEST';
export const PROFILE_FETCH_PUBLIC_SUCCESS = 'PROFILE_FETCH_PUBLIC_SUCCESS';
export const PROFILE_FETCH_PUBLIC_FAILED = 'PROFILE_FETCH_PUBLIC_FAILED';
export const PROFILE_FETCH_PUBLIC_RESET = 'PROFILE_FETCH_PUBLIC_RESET';

export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';

export const USER_POST_FETCH_REQUEST = 'USER_POST_FETCH_REQUEST';
export const USER_POST_FETCH_SUCCESS = 'USER_POST_FETCH_SUCCESS';
export const USER_POST_FETCH_FAILED = 'USER_POST_FETCH_FAILED';

export const PUBLIC_POST_FETCH_REQUEST = 'PUBLIC_POST_FETCH_REQUEST';
export const PUBLIC_POST_FETCH_SUCCESS = 'PUBLIC_POST_FETCH_SUCCESS';
export const PUBLIC_POST_FETCH_FAILED = 'PUBLIC_POST_FETCH_FAILED';

export const POST_SUBMIT_REQUEST = 'POST_SUBMIT_REQUEST';
export const POST_SUBMIT_SUCCESS = 'POST_SUBMIT_SUCCESS';
export const POST_SUBMIT_FAILED = 'POST_SUBMIT_FAILED';
