export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const PROFILE_FETCH_USER_REQUEST = 'PROFILE_FETCH_USER_REQUEST';
export const PROFILE_FETCH_USER_SUCCESS = 'PROFILE_FETCH_USER_SUCCESS';
export const PROFILE_FETCH_USER_FAILED = 'PROFILE_FETCH_USER_FAILED';
export const PROFILE_FETCH_USER_RESET = 'PROFILE_FETCH_USER_RESET';

export const PROFILE_FETCH_PUBLIC_REQUEST = 'PROFILE_FETCH_PUBLIC_REQUEST';
export const PROFILE_FETCH_PUBLIC_SUCCESS = 'PROFILE_FETCH_PUBLIC_SUCCESS';
export const PROFILE_FETCH_PUBLIC_FAILED = 'PROFILE_FETCH_PUBLIC_FAILED';
export const PROFILE_FETCH_PUBLIC_RESET = 'PROFILE_FETCH_PUBLIC_RESET';

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';
export const PROFILE_UPDATE_RESET = 'PROFILE_UPDATE_RESET';

export const PROFILE_DP_UPDATE_REQUEST = 'PROFILE_DP_UPDATE_REQUEST';
export const PROFILE_DP_UPDATE_SUCCESS = 'PROFILE_DP_UPDATE_SUCCESS';
export const PROFILE_DP_UPDATE_FAILED = 'PROFILE_DP_UPDATE_FAILED';
export const PROFILE_DP_UPDATE_RESET = 'PROFILE_DP_UPDATE_RESET';

export const PROFILE_COVER_UPDATE_REQUEST = 'PROFILE_COVER_UPDATE_REQUEST';
export const PROFILE_COVER_UPDATE_SUCCESS = 'PROFILE_COVER_UPDATE_SUCCESS';
export const PROFILE_COVER_UPDATE_FAILED = 'PROFILE_COVER_UPDATE_FAILED';
export const PROFILE_COVER_UPDATE_RESET = 'PROFILE_COVER_UPDATE_RESET';

export const USER_POST_FETCH_REQUEST = 'USER_POST_FETCH_REQUEST';
export const USER_POST_FETCH_SUCCESS = 'USER_POST_FETCH_SUCCESS';
export const USER_POST_FETCH_FAILED = 'USER_POST_FETCH_FAILED';

export const PUBLIC_POST_FETCH_REQUEST = 'PUBLIC_POST_FETCH_REQUEST';
export const PUBLIC_POST_FETCH_SUCCESS = 'PUBLIC_POST_FETCH_SUCCESS';
export const PUBLIC_POST_FETCH_FAILED = 'PUBLIC_POST_FETCH_FAILED';

export const POST_SUBMIT_REQUEST = 'POST_SUBMIT_REQUEST';
export const POST_SUBMIT_SUCCESS = 'POST_SUBMIT_SUCCESS';
export const POST_SUBMIT_FAILED = 'POST_SUBMIT_FAILED';
export const POST_SUBMIT_RESET = 'POST_SUBMIT_RESET';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAILED = 'POST_DETAILS_FAILED';
export const POST_DETAILS_RESET = 'POST_DETAILS_RESET';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAILED = 'POST_DELETE_FAILED';
export const POST_DELETE_RESET = 'POST_DELETE_RESET';

export const POST_EDIT_REQUEST = 'POST_EDIT_REQUEST';
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS';
export const POST_EDIT_FAILED = 'POST_EDIT_FAILED';
export const POST_EDIT_RESET = 'POST_EDIT_RESET';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';

export const FOLLOW_OTHERS_REQUEST = 'FOLLOW_OTHERS_REQUEST';
export const FOLLOW_OTHERS_SUCCESS = 'FOLLOW_OTHERS_SUCCESS';
export const FOLLOW_OTHERS_FAILED = 'FOLLOW_OTHERS_FAILED';
export const FOLLOW_OTHERS_RESET = 'FOLLOW_OTHERS_RESET';

export const UNFOLLOW_OTHERS_REQUEST = 'UNFOLLOW_OTHERS_REQUEST';
export const UNFOLLOW_OTHERS_SUCCESS = 'UNFOLLOW_OTHERS_SUCCESS';
export const UNFOLLOW_OTHERS_FAILED = 'UNFOLLOW_OTHERS_FAILED';
export const UNFOLLOW_OTHERS_RESET = 'UNFOLLOW_OTHERS_RESET';
